--------------------------------------------------------
--  Fichier créé - lundi-janvier-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ID_RDV_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOPTIMAL"."ID_RDV_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PATIENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOPTIMAL"."PATIENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RDV_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOPTIMAL"."RDV_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AMBULANCE
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."AMBULANCE" 
   (	"IMMATRICULE" NUMBER, 
	"AMBULANCIER" VARCHAR2(20 BYTE), 
	"MATERIEL_MEDICAL" VARCHAR2(60 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHAMBRE
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."CHAMBRE" 
   (	"EMPLACEMENT" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"NOMBRE_LITS" VARCHAR2(20 BYTE), 
	"NOM_SURVEILLANT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTENIR
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."CONTENIR" 
   (	"NUMERO_CHAMBRE" VARCHAR2(20 BYTE), 
	"NOM_SERVICE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMP
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."EMP" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"MNAME" VARCHAR2(20 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"NOM_SERVICE" VARCHAR2(20 BYTE), 
	"ID_MISSION" VARCHAR2(20 BYTE), 
	"ID_USER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENT
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."EQUIPEMENT" 
   (	"NOM" VARCHAR2(50 BYTE), 
	"DISPO" VARCHAR2(20 BYTE), 
	"ETAT_FONC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENTS
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."MEDICAMENTS" 
   (	"NAME" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"DF" VARCHAR2(31 BYTE), 
	"DLC" VARCHAR2(31 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"QUANTITE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MISSION
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."MISSION" 
   (	"ID" VARCHAR2(20 BYTE), 
	"DESTINATION" VARCHAR2(20 BYTE), 
	"HEURE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NECESSITER
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."NECESSITER" 
   (	"NOM_EQUIPEMENT" VARCHAR2(50 BYTE), 
	"NOM_SERVICE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."PATIENT" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATENAISSANCE" DATE, 
	"NUMCHAMBRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RDV
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."RDV" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOMPATIENT" VARCHAR2(20 BYTE), 
	"PRENOMPATIENT" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"DATETIME" TIMESTAMP (6), 
	"CIN_PATIENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICES
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."SERVICES" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"STAFF1" VARCHAR2(20 BYTE), 
	"STAFF2" VARCHAR2(20 BYTE), 
	"STAFF3" VARCHAR2(20 BYTE), 
	"NOM_EQUIPEMENT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SYS_USERS
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."SYS_USERS" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWD" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"MNAME" VARCHAR2(20 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"RANK" VARCHAR2(20 BYTE) DEFAULT 1, 
	"EMAIL" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISER
--------------------------------------------------------

  CREATE TABLE "HOPTIMAL"."UTILISER" 
   (	"ID_MISSION" VARCHAR2(20 BYTE), 
	"IMMATRICULE_AMBULANCE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HOPTIMAL.AMBULANCE
SET DEFINE OFF;
Insert into HOPTIMAL.AMBULANCE (IMMATRICULE,AMBULANCIER,MATERIEL_MEDICAL,ETAT) values ('415251','qdsqd','sqdsdq','sdq');
REM INSERTING into HOPTIMAL.CHAMBRE
SET DEFINE OFF;
Insert into HOPTIMAL.CHAMBRE (EMPLACEMENT,TYPE,NUMERO,NOMBRE_LITS,NOM_SURVEILLANT) values ('chirurgie','Chambre de garde','a1','5','emp1');
Insert into HOPTIMAL.CHAMBRE (EMPLACEMENT,TYPE,NUMERO,NOMBRE_LITS,NOM_SURVEILLANT) values ('chirurgie','Chambre de garde','a5','2','emp1');
Insert into HOPTIMAL.CHAMBRE (EMPLACEMENT,TYPE,NUMERO,NOMBRE_LITS,NOM_SURVEILLANT) values ('interne','Chambre du patient','741','4','emp4');
Insert into HOPTIMAL.CHAMBRE (EMPLACEMENT,TYPE,NUMERO,NOMBRE_LITS,NOM_SURVEILLANT) values ('pediatrie','Chambre de garde','qs','1','emp4');
Insert into HOPTIMAL.CHAMBRE (EMPLACEMENT,TYPE,NUMERO,NOMBRE_LITS,NOM_SURVEILLANT) values ('urgence','Chambre de garde','9','3','emp2');
Insert into HOPTIMAL.CHAMBRE (EMPLACEMENT,TYPE,NUMERO,NOMBRE_LITS,NOM_SURVEILLANT) values ('urgence','Chambre du patient','a52','1','emp3');
Insert into HOPTIMAL.CHAMBRE (EMPLACEMENT,TYPE,NUMERO,NOMBRE_LITS,NOM_SURVEILLANT) values ('ophtalmo','Guard room','5','4','emp1');
REM INSERTING into HOPTIMAL.CONTENIR
SET DEFINE OFF;
REM INSERTING into HOPTIMAL.EMP
SET DEFINE OFF;
Insert into HOPTIMAL.EMP (USERNAME,MNAME,LNAME,FNAME,EMAIL,ID,NOM_SERVICE,ID_MISSION,ID_USER) values ('emp1','aez','aez','zae','azeaze','1',null,null,null);
Insert into HOPTIMAL.EMP (USERNAME,MNAME,LNAME,FNAME,EMAIL,ID,NOM_SERVICE,ID_MISSION,ID_USER) values ('emp2','aez','aez','zae','azeaze','11',null,null,null);
Insert into HOPTIMAL.EMP (USERNAME,MNAME,LNAME,FNAME,EMAIL,ID,NOM_SERVICE,ID_MISSION,ID_USER) values ('emp3','aez','aez','zae','azeaze','111',null,null,null);
Insert into HOPTIMAL.EMP (USERNAME,MNAME,LNAME,FNAME,EMAIL,ID,NOM_SERVICE,ID_MISSION,ID_USER) values ('emp4','dqsqa','qsd','qds','qsdqd','252',null,null,null);
REM INSERTING into HOPTIMAL.EQUIPEMENT
SET DEFINE OFF;
Insert into HOPTIMAL.EQUIPEMENT (NOM,DISPO,ETAT_FONC) values ('scan','1','1');
Insert into HOPTIMAL.EQUIPEMENT (NOM,DISPO,ETAT_FONC) values ('scan1','1','1');
Insert into HOPTIMAL.EQUIPEMENT (NOM,DISPO,ETAT_FONC) values ('scnahjqsd','1','0');
Insert into HOPTIMAL.EQUIPEMENT (NOM,DISPO,ETAT_FONC) values ('table','1','1');
Insert into HOPTIMAL.EQUIPEMENT (NOM,DISPO,ETAT_FONC) values ('aaaa','1','0');
REM INSERTING into HOPTIMAL.MEDICAMENTS
SET DEFINE OFF;
Insert into HOPTIMAL.MEDICAMENTS (NAME,DESCRIPTION,DF,DLC,PRIX,QUANTITE) values ('aaaaaaze','qsdqd','14-09-2015','01-01-2020','100','20');
Insert into HOPTIMAL.MEDICAMENTS (NAME,DESCRIPTION,DF,DLC,PRIX,QUANTITE) values ('test','aze','14-09-2015','01-01-2020','5000','20');
Insert into HOPTIMAL.MEDICAMENTS (NAME,DESCRIPTION,DF,DLC,PRIX,QUANTITE) values ('med2','zea','14-09-2015','01-01-2020','1000','80');
Insert into HOPTIMAL.MEDICAMENTS (NAME,DESCRIPTION,DF,DLC,PRIX,QUANTITE) values ('zaazeza','azez','14-09-2015','01-01-2020','852','10');
REM INSERTING into HOPTIMAL.MISSION
SET DEFINE OFF;
Insert into HOPTIMAL.MISSION (ID,DESTINATION,HEURE) values ('1234512','zae','zea');
REM INSERTING into HOPTIMAL.NECESSITER
SET DEFINE OFF;
REM INSERTING into HOPTIMAL.PATIENT
SET DEFINE OFF;
Insert into HOPTIMAL.PATIENT (CIN,NOM,PRENOM,DATENAISSANCE,NUMCHAMBRE) values ('00000002','bouzaiene','dali',to_date('21/08/00','DD/MM/RR'),'a1');
Insert into HOPTIMAL.PATIENT (CIN,NOM,PRENOM,DATENAISSANCE,NUMCHAMBRE) values ('10000000','dali','azeza',to_date('21/08/00','DD/MM/RR'),'a1');
Insert into HOPTIMAL.PATIENT (CIN,NOM,PRENOM,DATENAISSANCE,NUMCHAMBRE) values ('15255152','azeae','aezaz',to_date('21/08/00','DD/MM/RR'),'a5');
Insert into HOPTIMAL.PATIENT (CIN,NOM,PRENOM,DATENAISSANCE,NUMCHAMBRE) values ('10156119','ghzaasd','qsdsqd',to_date('21/08/00','DD/MM/RR'),'a5');
Insert into HOPTIMAL.PATIENT (CIN,NOM,PRENOM,DATENAISSANCE,NUMCHAMBRE) values ('47815203','mhedhbi','meriam',to_date('21/08/00','DD/MM/RR'),'a1');
Insert into HOPTIMAL.PATIENT (CIN,NOM,PRENOM,DATENAISSANCE,NUMCHAMBRE) values ('14000000','this','zerty',to_date('21/08/00','DD/MM/RR'),'a1');
Insert into HOPTIMAL.PATIENT (CIN,NOM,PRENOM,DATENAISSANCE,NUMCHAMBRE) values ('05145121','ben smida','meaher',to_date('21/08/00','DD/MM/RR'),'a1');
REM INSERTING into HOPTIMAL.RDV
SET DEFINE OFF;
Insert into HOPTIMAL.RDV (ID,NOMPATIENT,PRENOMPATIENT,EMAIL,DATETIME,CIN_PATIENT) values ('5','test','test','test.test@test.test',to_timestamp('31/12/20 20:26:54,000000000','DD/MM/RR HH24:MI:SSXFF'),null);
Insert into HOPTIMAL.RDV (ID,NOMPATIENT,PRENOMPATIENT,EMAIL,DATETIME,CIN_PATIENT) values ('3','mhedhbi','meriam','meriam.mhedhbi@esprit.tn',to_timestamp('28/12/20 17:02:23,000000000','DD/MM/RR HH24:MI:SSXFF'),null);
Insert into HOPTIMAL.RDV (ID,NOMPATIENT,PRENOMPATIENT,EMAIL,DATETIME,CIN_PATIENT) values ('4','bouzaiene','mohamed ali','mohamedali.bouzaiene@esprit.tn',to_timestamp('28/12/20 17:06:53,000000000','DD/MM/RR HH24:MI:SSXFF'),null);
Insert into HOPTIMAL.RDV (ID,NOMPATIENT,PRENOMPATIENT,EMAIL,DATETIME,CIN_PATIENT) values ('6','mhedhbi','meriam','meriam.mhedhbi@esprit.tn',to_timestamp('04/01/21 17:12:50,000000000','DD/MM/RR HH24:MI:SSXFF'),null);
REM INSERTING into HOPTIMAL.SERVICES
SET DEFINE OFF;
Insert into HOPTIMAL.SERVICES (NOM,STAFF1,STAFF2,STAFF3,NOM_EQUIPEMENT) values ('chirurgie','emp1','emp3','emp2','scan1');
Insert into HOPTIMAL.SERVICES (NOM,STAFF1,STAFF2,STAFF3,NOM_EQUIPEMENT) values ('interne','emp4','emp1','emp2','scnahjqsd');
Insert into HOPTIMAL.SERVICES (NOM,STAFF1,STAFF2,STAFF3,NOM_EQUIPEMENT) values ('ophtalmo','emp2','emp3','emp4','scan');
REM INSERTING into HOPTIMAL.SYS_USERS
SET DEFINE OFF;
Insert into HOPTIMAL.SYS_USERS (ID,USERNAME,PASSWD,FNAME,MNAME,LNAME,RANK,EMAIL) values (null,'Dali','0001','azeaze','azeaze','azeaz','1','azea@aze.com');
Insert into HOPTIMAL.SYS_USERS (ID,USERNAME,PASSWD,FNAME,MNAME,LNAME,RANK,EMAIL) values (null,'Jasser','0001','sdqqs','dqq','dqqds','-1','qqsd');
Insert into HOPTIMAL.SYS_USERS (ID,USERNAME,PASSWD,FNAME,MNAME,LNAME,RANK,EMAIL) values (null,'Sahar','0001','azesqd','qdsqsd','qsdsqd','1','vygbhnj@sqd');
REM INSERTING into HOPTIMAL.UTILISER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger RDV_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOPTIMAL"."RDV_BI" 
BEFORE INSERT ON rdv
FOR EACH ROW
BEGIN
  SELECT PATIENTS_SEQ.nextval
  INTO :new.id
  FROM dual;
END;
/
ALTER TRIGGER "HOPTIMAL"."RDV_BI" ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDICAMENTS
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."MEDICAMENTS" ADD PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOPTIMAL"."MEDICAMENTS" MODIFY ("QUANTITE" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."MEDICAMENTS" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."MEDICAMENTS" MODIFY ("DLC" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."MEDICAMENTS" MODIFY ("DF" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."MEDICAMENTS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."MEDICAMENTS" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."EQUIPEMENT" ADD PRIMARY KEY ("NOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOPTIMAL"."EQUIPEMENT" MODIFY ("ETAT_FONC" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."EQUIPEMENT" MODIFY ("DISPO" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."EQUIPEMENT" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_USERS
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."SYS_USERS" ADD PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."EMP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOPTIMAL"."EMP" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."EMP" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."EMP" MODIFY ("FNAME" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."EMP" MODIFY ("LNAME" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."EMP" MODIFY ("MNAME" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."EMP" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AMBULANCE
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."AMBULANCE" ADD PRIMARY KEY ("IMMATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOPTIMAL"."AMBULANCE" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."AMBULANCE" MODIFY ("MATERIEL_MEDICAL" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."AMBULANCE" MODIFY ("AMBULANCIER" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."AMBULANCE" MODIFY ("IMMATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."PATIENT" ADD PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOPTIMAL"."PATIENT" MODIFY ("NUMCHAMBRE" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."PATIENT" MODIFY ("DATENAISSANCE" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."PATIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."PATIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."PATIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MISSION
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."MISSION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOPTIMAL"."MISSION" MODIFY ("HEURE" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."MISSION" MODIFY ("DESTINATION" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."MISSION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."SERVICES" ADD PRIMARY KEY ("NOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHAMBRE
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."CHAMBRE" ADD PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RDV
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."RDV" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOPTIMAL"."RDV" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."RDV" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."RDV" MODIFY ("PRENOMPATIENT" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."RDV" MODIFY ("NOMPATIENT" NOT NULL ENABLE);
  ALTER TABLE "HOPTIMAL"."RDV" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONTENIR
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."CONTENIR" ADD CONSTRAINT "FK_NOMSERVICE" FOREIGN KEY ("NOM_SERVICE")
	  REFERENCES "HOPTIMAL"."SERVICES" ("NOM") ENABLE;
  ALTER TABLE "HOPTIMAL"."CONTENIR" ADD CONSTRAINT "FK_NUMEROCHAMBRE" FOREIGN KEY ("NUMERO_CHAMBRE")
	  REFERENCES "HOPTIMAL"."CHAMBRE" ("NUMERO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMP
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."EMP" ADD CONSTRAINT "FK_IDMISSION2" FOREIGN KEY ("ID_MISSION")
	  REFERENCES "HOPTIMAL"."MISSION" ("ID") ENABLE;
  ALTER TABLE "HOPTIMAL"."EMP" ADD CONSTRAINT "FK_NOMSERVICE2" FOREIGN KEY ("NOM_SERVICE")
	  REFERENCES "HOPTIMAL"."SERVICES" ("NOM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NECESSITER
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."NECESSITER" ADD CONSTRAINT "FK_NOMEQUIPEMENT1" FOREIGN KEY ("NOM_EQUIPEMENT")
	  REFERENCES "HOPTIMAL"."EQUIPEMENT" ("NOM") ENABLE;
  ALTER TABLE "HOPTIMAL"."NECESSITER" ADD CONSTRAINT "FK_NOMSERVICE1" FOREIGN KEY ("NOM_SERVICE")
	  REFERENCES "HOPTIMAL"."SERVICES" ("NOM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."PATIENT" ADD CONSTRAINT "FK_NUMCHAMBRE" FOREIGN KEY ("NUMCHAMBRE")
	  REFERENCES "HOPTIMAL"."CHAMBRE" ("NUMERO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RDV
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."RDV" ADD CONSTRAINT "FK_CINPATIENT" FOREIGN KEY ("CIN_PATIENT")
	  REFERENCES "HOPTIMAL"."PATIENT" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."SERVICES" ADD CONSTRAINT "FK_NOMEQUIPEMENT" FOREIGN KEY ("NOM_EQUIPEMENT")
	  REFERENCES "HOPTIMAL"."EQUIPEMENT" ("NOM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTILISER
--------------------------------------------------------

  ALTER TABLE "HOPTIMAL"."UTILISER" ADD CONSTRAINT "FK_ID" FOREIGN KEY ("ID_MISSION")
	  REFERENCES "HOPTIMAL"."MISSION" ("ID") ENABLE;
  ALTER TABLE "HOPTIMAL"."UTILISER" ADD CONSTRAINT "FK_IM" FOREIGN KEY ("IMMATRICULE_AMBULANCE")
	  REFERENCES "HOPTIMAL"."AMBULANCE" ("IMMATRICULE") ENABLE;
